package com.gozero.reconciliation.web;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.Instant;

/** Every reconciliation response is explicitly labelled SIMULATED and never isLiveData=true. */
public record ApiEnvelope<T>(
        String dataSource,
        @JsonProperty("isLiveData") boolean isLiveData,
        boolean referencePriceIsLive,
        String note,
        Instant generatedAt,
        int count,
        T data) {

    public static final String SIMULATED = "SIMULATED";

    public static <T> ApiEnvelope<T> simulated(boolean referencePriceIsLive, int count, T data) {
        String note = "SIMULATED DATA: Blinkit, Zepto and Instamart price/stock are generated by reconciliation-service "
                + "(seeded random, +/-5% jitter with deliberately injected anomalies). They are NOT real platform data. "
                + "Only the BigBasket reference price comes from ingestion-service ("
                + (referencePriceIsLive ? "live scrape" : "seed dataset, also not live") + ").";
        return new ApiEnvelope<>(SIMULATED, false, referencePriceIsLive, note, Instant.now(), count, data);
    }
}
